// Generated by scripts/build-site.mjs - do not edit; change public/viewer.config.js.
import base from './viewer.base.js?v=mv2lq84c';

const rel = (u) => (u ? String(u).replace(/^\//, '') : u);

export default {
  ...base,
  modelUrl: 'data/model.bin',
  packsBase: 'models',
  refreshUrl: null,
  autoUpdate: "Updates automatically at 11 am and 5 pm IST",
  logos: (base.logos ?? []).map((l) => ({ ...l, light: rel(l.light), dark: rel(l.dark) })),
  favicon: rel(base.favicon),
  encrypted: {"salt":"/jeOhp0WkkzUMfonQetvbg==","iter":600000,"check":"1cMeM1X/2elxaI9PLt48tYEvnYdPALdz0rJrUyi2B21wj22og/RYpyR6vIQyzDC1V5wkaJFhK0L3VxTj","sizes":{"data/model.bin":436761,"models/m3m-residential-towers-str-tower-a-1-typical-ver1.json":6079,"models/m3m-residential-towers-str-tower-a-1-typical-ver1.bin":6377961,"models/m3m-residential-towers-str-tower-a2-typical-ver1.json":6319,"models/m3m-residential-towers-str-tower-a2-typical-ver1.bin":4717607,"models/m3m-residential-towers-str-tower-b-typical-ver2.json":5786,"models/m3m-residential-towers-str-tower-b-typical-ver2.bin":6155761,"models/m3m-residential-towers-str-tower-c-typical-ver1.json":10575,"models/m3m-residential-towers-str-tower-c-typical-ver1.bin":5379078},"note":"Protected. Ask your VisiLean contact for the password."},
};
